ci: increase memory to mitigate (#2132)
## Summary

The sum of the memory was larger than the container. 
```
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: TaskManager memory configuration failed: Sum of configured Framework Heap Memory (128.000mb (134217728 bytes)), Framework Off-Heap Memory (128.000mb (134217728 bytes)), Task Off-Heap Memory (1024.000mb (1073741824 bytes)), Managed Memory (1.550gb (1664299824 bytes)) and Network Memory (1024.000mb (1073741824 bytes)) exceed configured Total Flink Memory (3.100gb (3328599648 bytes)).
```
Increased container for now while I look into
https://linear.app/zipline-ai/issue/CTRL-286/apply-task-manager-memory-tiers-to-dataproc

## Checklist
- [ ] Added Unit Tests
- [ ] Covered by existing CI
- [x] Integration tested
```
!  8/28/2026 11:52:28.614 AM  Illegal reflective access by org.apache.spark.unsafe.Platform (file:/tmp/72dcea80-05d3-4cf0-832e-fde47ec966ae/flink_assembly_deploy.jar) to constructor java.nio.DirectByteBuffer(long,int)
!  8/28/2026 11:52:28.614 AM  Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
!  8/28/2026 11:52:28.614 AM  Use --illegal-access=warn to enable warnings of further illegal reflective access operations
!  8/28/2026 11:52:28.614 AM  All illegal access operations will be denied in a future release
!  8/28/2026 11:52:33.103 AM  2026-08-28 18:52:33,102 WARN  org.apache.flink.yarn.configuration.YarnLogConfigUtil        [] - The configuration directory ('/etc/flink/conf.dist') already contains a LOG4J config file.If you want to use logback, then please delete or rename the log configuration file.
i  8/28/2026 11:52:33.358 AM  2026-08-28 18:52:33,357 INFO  org.apache.hadoop.yarn.client.DefaultNoHARMFailoverProxyProvider [] - Connecting to ResourceManager at zipline-canary-cluster-m.us-central1-a.c.canary-443022.internal./10.0.0.2:8032
i  8/28/2026 11:52:33.576 AM  2026-08-28 18:52:33,576 INFO  org.apache.hadoop.yarn.client.AHSProxy                       [] - Connecting to Application History server at zipline-canary-cluster-m.us-central1-a.c.canary-443022.internal./10.0.0.2:10200
i  8/28/2026 11:52:33.588 AM  2026-08-28 18:52:33,588 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - No path for the flink jar passed. Using the location of class org.apache.flink.yarn.YarnClusterDescriptor to locate the jar
!  8/28/2026 11:52:33.607 AM  2026-08-28 18:52:33,607 WARN  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Job Clusters are deprecated since Flink 1.15. Please use an Application Cluster/Application Mode instead.
i  8/28/2026 11:52:33.808 AM  2026-08-28 18:52:33,808 INFO  org.apache.hadoop.conf.Configuration                         [] - resource-types.xml not found
i  8/28/2026 11:52:33.809 AM  2026-08-28 18:52:33,808 INFO  org.apache.hadoop.yarn.util.resource.ResourceUtils           [] - Unable to find 'resource-types.xml'.
i  8/28/2026 11:52:33.873 AM  2026-08-28 18:52:33,872 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Cluster specification: ClusterSpecification{masterMemoryMB=4096, taskManagerMemoryMB=16384, slotsPerTaskManager=4}
!  8/28/2026 11:52:34.901 AM  2026-08-28 18:52:34,901 WARN  org.apache.hadoop.hdfs.shortcircuit.DomainSocketFactory      [] - The short-circuit local reads feature cannot be used because libhadoop cannot be loaded.
i  8/28/2026 11:52:39.091 AM  2026-08-28 18:52:39,091 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Removing 'localhost' Key: 'jobmanager.bind-host' , default: null (fallback keys: []) setting from effective configuration; using '0.0.0.0' instead.
i  8/28/2026 11:52:39.092 AM  2026-08-28 18:52:39,092 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Removing 'localhost' Key: 'taskmanager.bind-host' , default: null (fallback keys: []) setting from effective configuration; using '0.0.0.0' instead.
i  8/28/2026 11:52:39.128 AM  2026-08-28 18:52:39,128 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Cannot use kerberos delegation token manager, no valid kerberos credentials provided.
i  8/28/2026 11:52:39.134 AM  2026-08-28 18:52:39,134 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Submitting application master application_1781299767084_6789
i  8/28/2026 11:52:39.181 AM  2026-08-28 18:52:39,180 INFO  org.apache.hadoop.yarn.client.api.impl.YarnClientImpl        [] - Submitted application application_1781299767084_6789
i  8/28/2026 11:52:39.181 AM  2026-08-28 18:52:39,181 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Waiting for the cluster to be allocated
i  8/28/2026 11:52:39.182 AM  2026-08-28 18:52:39,182 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Deploying cluster, current state ACCEPTED
i  8/28/2026 11:52:50.231 AM  2026-08-28 18:52:50,231 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - YARN application has been deployed successfully.
i  8/28/2026 11:52:50.232 AM  2026-08-28 18:52:50,232 INFO  org.apache.flink.yarn.YarnClusterDescriptor                  [] - Found Web Interface zipline-canary-cluster-w-8.us-central1-a.c.canary-443022.internal:33009 of application 'application_1781299767084_6789'.
*  8/28/2026 11:52:50.241 AM  Job has been submitted with JobID 56b15215a893510401ab96afca14087e
```
- [ ] Documentation update